name: deokive-stack

services:
  backend:
    container_name: deokive-backend
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/${ECR_REPO}:latest
    platform: linux/arm64
    pull_policy: always
    restart: always
    ports:
        - "8080:8080"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - MAX_REQUEST_SIZE=${MAX_REQUEST_SIZE}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRATION_MINUTES=${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES}
      - JWT_REFRESH_TOKEN_EXPIRATION_WEEKS=${JWT_REFRESH_TOKEN_EXPIRATION_WEEKS}
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
        - deokive-network

  mysql:
    container_name: mysql-container
    image: mysql:8.0.39
    platform: linux/arm64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Asia/Seoul
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}" ]
      interval: 5s
      retries: 10
    networks:
      - deokive-network

  redis:
    container_name: redis-container
    image: redis:7.2-alpine
    platform: linux/arm64
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 10
    networks:
      - deokive-network

networks:
  deokive-network:
    driver: bridge
