name: deokive-stack

services:
  backend:
    deploy:
      resources:
        limits:
          memory: "768m"     # t4g.small 환경에서 권장(시작은 768m~1024m)
        reservations:
          memory: "512m"
    container_name: deokive-backend
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.ap-northeast-2.amazonaws.com/${ECR_REPO}:latest
    platform: linux/arm64
    pull_policy: always
    restart: always
    ports:
        - "8080:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-Xms256m -Xmx512m -XX:MaxMetaspaceSize=192m -XX:+UseContainerSupport -XX:MaxRAMPercentage=60.0
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME}
      - MAX_FILE_SIZE=${MAX_FILE_SIZE}
      - MAX_REQUEST_SIZE=${MAX_REQUEST_SIZE}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ACCESS_TOKEN_EXPIRATION_MINUTES=${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES}
      - JWT_REFRESH_TOKEN_EXPIRATION_WEEKS=${JWT_REFRESH_TOKEN_EXPIRATION_WEEKS}
      - OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID}
      - OAUTH_GOOGLE_CLIENT_SECRET=${OAUTH_GOOGLE_CLIENT_SECRET}
      - OAUTH_KAKAO_CLIENT_ID=${OAUTH_KAKAO_CLIENT_ID}
      - OAUTH_KAKAO_CLIENT_SECRET=${OAUTH_KAKAO_CLIENT_SECRET}
      - OAUTH_NAVER_CLIENT_ID=${OAUTH_NAVER_CLIENT_ID}
      - OAUTH_NAVER_CLIENT_SECRET=${OAUTH_NAVER_CLIENT_SECRET}
      - HMAC_SECRET_KEY=${HMAC_SECRET_KEY}
      - TZ=Asia/Seoul
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
        - deokive-network

  mysql:
    container_name: mysql-container
    image: mysql:8.0.39
    platform: linux/arm64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: Asia/Seoul
    volumes:
      - ./mysql-data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-p${DB_PASSWORD}" ]
      interval: 5s
      retries: 10
    networks:
      - deokive-network

  redis:
    container_name: redis-container
    image: redis:7.2-alpine
    platform: linux/arm64
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping" ]
      interval: 5s
      retries: 10
    networks:
      - deokive-network

networks:
  deokive-network:
    driver: bridge
