server:
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # 개발 단계에서는 한시적으로 허용하고, 운영 단계에서는 validate 또는 none으로 변경하는 것을 권장.

logging:
  level:
    org.hibernate.SQL: off # select u1_0.id, u1_0.username, u1_0.email from user u1_0 이런거 안찍겠다.
    org.hibernate.type: off # select * from user where email=?binding parameter [1] as [VARCHAR] - [test@example.com] 이런거 안찍겠다.

jwt:
  secret: ${JWT_SECRET_KEY}
  atk-exp-min: ${JWT_ACCESS_TOKEN_EXPIRATION_MINUTES:30}
  rtk-exp-week: ${JWT_REFRESH_TOKEN_EXPIRATION_WEEKS:2}

app:
  cookie:
    secure: true
    cookie-atk: "ATK"
    cookie-rtk: "RTK"
    same-site: "None"  # 크로스 사이트 쿠키 전송을 위해 None으로 설정 (Secure=true와 함께 사용)
    domain: "${COOKIE_DOMAIN}"
    atk-apply-path: "/"
    rtk-apply-path: "/api/v1/"  # refresh와 logout 엔드포인트 모두에서 접근 가능하도록 변경
